# Generated by Django 3.2.12 on 2022-03-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0010_alter_demand_has_revision'),
        ('tracking', '0003_alter_pageview_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='demand',
            field=models.ManyToManyField(related_name='pageviews', to='demand.Demand'),
        ),
    ]
