# Generated by Django 3.2.12 on 2022-02-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20220226_1212'),
        ('demand', '0004_auto_20220219_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='category',
            field=models.ManyToManyField(related_name='taxonomy_category', to='category.Category'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='service',
            field=models.ManyToManyField(related_name='taxonomy_service', to='category.Service'),
        ),
    ]
