# Generated by Django 3.2.12 on 2022-03-05 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0003_auto_20220226_1212'),
        ('demand', '0005_auto_20220226_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demand',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Texte', 'verbose_name_plural': 'Textes'},
        ),
        migrations.RenameField(
            model_name='demand',
            old_name='edited',
            new_name='verified',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='image',
        ),
        migrations.AlterField(
            model_name='demand',
            name='category',
            field=models.ManyToManyField(related_name='category', to='category.Category'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='service',
            field=models.ManyToManyField(related_name='service', to='category.Service'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
    ]
