# Generated by Django 3.2.12 on 2022-03-25 18:36

import django.core.validators
from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0010_alter_demand_has_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Text'),
        ),
    ]
