# Generated by Django 3.2.12 on 2022-04-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0012_auto_20220422_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='tokens',
            field=models.TextField(blank=True, help_text='nécessaire pour la recherche et le SEO', verbose_name='SEO/Recherche'),
        ),
    ]
