# Generated by Django 3.2.13 on 2022-06-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0014_auto_20220429_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
