# Generated by Django 3.2.10 on 2022-02-19 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand', '0004_auto_20220219_1042'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='demand',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand', to='demand.demand'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
