# Generated by Django 3.2.12 on 2022-02-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_image_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='articles/%Y/%m/%d/', verbose_name='Featured image'),
            preserve_default=False,
        ),
    ]
