# Generated by Django 3.2.12 on 2022-03-25 18:36

import django.core.validators
from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20220323_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='Contenu'),
        ),
    ]
