# Generated by Django 3.2.12 on 2022-04-22 23:25

import bootcamp.custom
from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(validators=[bootcamp.custom.word_counter_validator], verbose_name='Contenu'),
        ),
    ]
