# Generated by Django 3.0.3 on 2020-04-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
        ("category", "0002_add_icon_path_field"),
    ]

    operations = [
    
         migrations.AddField(
            model_name="category",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True),
        ),
         migrations.AddField(
            model_name="category",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True),
        )
        
    ]
